[[mounts]]
disable = false
what = "UUID=2ebdaf8a-2dee-4812-9c86-525d9b742ff2"
where = "/srv/storage/data"
type = "btrfs"
options = "defaults,rw,compress=zstd,subvol=data"
target = "" # defaults to multi-user.target
